# Generated by Django 5.1.6 on 2025-03-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pet_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
