# Generated by Django 5.1.6 on 2025-04-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Grooming", "Grooming"),
                    ("Health", "Health"),
                    ("Home", "Home"),
                    ("Training", "Training"),
                    ("Lifestyle", "Lifestyle"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="slot",
            field=models.CharField(
                blank=True,
                choices=[
                    ("07:00 - 08:00", "07:00 - 08:00"),
                    ("08:00 - 09:00", "08:00 - 09:00"),
                    ("09:00 - 10:00", "09:00 - 10:00"),
                    ("10:00 - 11:00", "10:00 - 11:00"),
                    ("11:00 - 12:00", "11:00 - 12:00"),
                    ("12:00 - 13:00", "12:00 - 13:00"),
                    ("13:00 - 14:00", "13:00 - 14:00"),
                    ("14:00 - 15:00", "14:00 - 15:00"),
                    ("15:00 - 16:00", "15:00 - 16:00"),
                    ("16:00 - 17:00", "16:00 - 17:00"),
                    ("17:00 - 18:00", "17:00 - 18:00"),
                    ("18:00 - 19:00", "18:00 - 19:00"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
