# Generated by Django 5.1.6 on 2025-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_service_preferred_slot_servicebooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="service_bookings",
            field=models.ManyToManyField(blank=True, to="myapp.servicebooking"),
        ),
    ]
